apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "challenge-skeleton-deployment"
  namespace: "default"
  labels:
    app: "challenge-skeleton"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "challenge-skeleton"
  template:
    metadata:
      labels:
        app: "challenge-skeleton"
      annotations:
        container.apparmor.security.beta.kubernetes.io/challenge-skeleton: unconfined
    spec:
      containers:
      - name: "challenge-skeleton"
        # this will be updated to eu.gcr.io/$project/$challenge-dir using kustomization.yaml in the kctf-conf
        image: "challenge-skeleton"
        ports:
        - containerPort: 1337
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
          readOnlyRootFilesystem: true
        command:
        volumeMounts:
        - name: "flag"
          mountPath: "/flag"
          subPath: "flag"
          readOnly: true
        - name: "pow"
          mountPath: "/pow"
          subPath: "pow"
          readOnly: true
        - name: "cgroup"
          subPath: "cpu/NSJAIL/challenge-skeleton"
          mountPath: "/cgroup/cpu/NSJAIL"
          readOnly: false
        - name: "cgroup"
          subPath: "memory/NSJAIL/challenge-skeleton"
          mountPath: "/cgroup/memory/NSJAIL"
          readOnly: false
        - name: "cgroup"
          subPath: "pids/NSJAIL/challenge-skeleton"
          mountPath: "/cgroup/pids/NSJAIL"
          readOnly: false
      initContainers:
      - name: "cgroup-setup"
        image: "busybox"
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
        command: ["sh", "-c", "for res in cpu memory pids; do mkdir -p /sys/fs/cgroup/${res}/NSJAIL && mkdir -m 0777 -p /sys/fs/cgroup/${res}/NSJAIL/challenge-skeleton; done"]
        volumeMounts:
        - name: "cgroup"
          mountPath: "/sys/fs/cgroup"
          readOnly: false
      volumes:
      - name: "flag"
        secret:
          # must be called ${challenge-dir}-flag
          secretName: "challenge-skeleton-flag"
          defaultMode: 0444
      - name: "pow"
        configMap:
          # must be called ${challenge-dir}-pow
          name: "challenge-skeleton-pow"
      - name: "cgroup"
        hostPath:
          path: /sys/fs/cgroup
